# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-27 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('team1f', models.CharField(blank=True, default=b'', max_length=100)),
                ('team1b', models.CharField(blank=True, default=b'', max_length=100)),
                ('team2f', models.CharField(blank=True, default=b'', max_length=100)),
                ('team2b', models.CharField(blank=True, default=b'', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True, verbose_name=b'date created')),
            ],
        ),
    ]
