# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-30 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameperformance',
            name='crawling',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gameperformance',
            name='owngoals',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
